export default {
  actions: {
    description: 'Descriptions of actions',
    fields: [
      'actionAgency',
      'actionId',
      'actionName',
      'assessmentUnitId',
      'assessmentUnitName',
      'completionDate',
      'inIndianCountry',
      'includeInMeasure',
      'organizationId',
      'organizationName',
      'parameter',
      'region',
      'state',
      'waterType',
    ],
    label: 'Actions',
    resource: 'actions',
  },
  assessmentUnits: {
    description: 'Description of assessment units',
    fields: [
      'assessmentUnitId',
      'assessmentUnitName',
      'assessmentUnitState',
      'locationText',
      'organizationId',
      'organizationName',
      'region',
      'state',
      'useClassName',
      'waterType',
    ],
    label: 'Assessment Units',
    resource: 'assessmentUnits',
  },
  assessments: {
    description: 'Description of assessments',
    fields: [
      'alternateListingIdentifier',
      'assessmentBasis',
      'assessmentDateLo',
      'assessmentDateHi',
      'assessmentMethods',
      'assessmentTypes',
      'assessmentUnitId',
      'assessmentUnitName',
      'assessmentUnitStatus',
      'associatedActionAgency',
      'associatedActionId',
      'associatedActionName',
      'associatedActionStatus',
      'associatedActionType',
      'consentDegreeCycleLo',
      'consentDegreeCycleHi',
      'cwa303dPriorityRanking',
      'cycleExpectedToAttainLo',
      'cycleExpectedToAttainHi',
      'cycleFirstListedLo',
      'cycleFirstListedHi',
      'cycleLastAssessedLo',
      'cycleLastAssessedHi',
      'cycleScheduledForTmdlLo',
      'cycleScheduledForTmdlHi',
      'delisted',
      'delistedReason',
      'epaIrCategory',
      'monitoringEndDateLo',
      'monitoringEndDateHi',
      'monitoringStartDateLo',
      'monitoringStartDateHi',
      'organizationId',
      'organizationName',
      'overallStatus',
      'parameterAttainment',
      'parameterGroup',
      'parameterIrCategory',
      'parameterName',
      'parameterStateIrCategory',
      'parameterStatus',
      'pollutantIndicator',
      'region',
      'reportingCycleLo',
      'reportingCycleHi',
      'seasonEndDateLo',
      'seasonEndDateHi',
      'seasonStartDateLo',
      'seasonStartDateHi',
      'state',
      'stateIrCategory',
      'useClassName',
      'useIrCategory',
      'useGroup',
      'useName',
      'useStateIrCategory',
      'useSupport',
      'vision303dPriority',
      'waterType',
    ],
    label: 'Assessments',
    resource: 'assessments',
  },
  assessmentUnitsMonitoringLocations: {
    description: 'Description of assessment units with monitoring locations',
    fields: [
      'assessmentUnitId',
      'assessmentUnitName',
      'assessmentUnitStatus',
      'monitoringLocationDataLink',
      'monitoringLocationId',
      'monitoringLocationOrgId',
      'organizationId',
      'organizationName',
      'region',
      'reportingCycleLo',
      'reportingCycleHi',
      'state',
      'useClassName',
      'waterType',
    ],
    label: 'Assessment Units with Monitoring Locations',
    resource: 'assessmentUnitsMonitoringLocations',
  },
  catchmentCorrespondence: {
    description: 'Description of Catchment Correspondence',
    fields: [
      'assessmentUnitId',
      'assessmentUnitName',
      'catchmentNhdplusId',
      'organizationId',
      'organizationName',
      'region',
      'reportingCycleLo',
      'reportingCycleHi',
      'state',
    ],
    label: 'Catchment Correspondence',
    resource: 'catchmentCorrespondence',
  },
  sources: {
    description: 'Description of Sources',
    fields: [
      'assessmentUnitId',
      'assessmentUnitName',
      'causeName',
      'confirmed',
      'epaIrCategory',
      'organizationId',
      'organizationName',
      'overallStatus',
      'parameterGroup',
      'region',
      'reportingCycleLo',
      'reportingCycleHi',
      'sourceName',
      'state',
      'stateIrCategory',
      'waterType',
    ],
    label: 'Sources',
    resource: 'sources',
  },
  tmdl: {
    description: 'Description of Total Maximum Daily Load',
    fields: [
      'actionAgency',
      'actionId',
      'actionName',
      'addressedParameter',
      'assessmentUnitId',
      'assessmentUnitName',
      'assessmentUnitStatus',
      'completionDateLo',
      'completionDateHi',
      'explicitMarginOfSafety',
      'fiscalYearEstablishedLo',
      'fiscalYearEstablishedHi',
      'implicitMarginOfSafety',
      'inIndianCountry',
      'includeInMeasure',
      'loadAllocation',
      'loadAllocationUnits',
      'npdesIdentifier',
      'organizationId',
      'organizationName',
      'otherIdentifier',
      'pollutant',
      'region',
      'sourceType',
      'tmdlDateLo',
      'tmdlDateHi',
      'tmdlEndpoint',
      'wasteLoadAllocation',
      'waterType',
    ],
    label: 'Total Maximum Daily Load',
    resource: 'tmdl',
  },
} as const;
